# Generated by Django 4.2.7 on 2023-12-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_guitarra_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='descripcion',
            field=models.CharField(default='Descripción del país', max_length=200),
        ),
    ]
