# Generated by Django 4.2.7 on 2023-12-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_pais_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pais',
            name='abreviacion',
            field=models.CharField(default='MX', max_length=5),
        ),
    ]
