# Generated by Django 4.2.7 on 2023-12-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_pais_descripcion_pais_abreviacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.marca'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='tipo_guitarra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.tipoguitarra'),
        ),
    ]
